models:
  - name: core_keyboards
    description: "all columns from joining base_keyboard_details and base_purchase_options models"
    columns:
      - name: product_tilte
        data_type: string
        description: "title of product in category page"

      - name: product_price
        data_type: int64
        description: "price of product in category page"

      - name: category_vendor
        data_type: string
        description: "product vendor appears inside 'View on' tag in category page"

      - name: category_voucher
        data_type: float64
        description: "coupon in category page"

      - name: is_new
        data_type: string
        description: "whether a new tag in product tile in category page"

      - name: listing_link
        data_type: string
        description: "detail listing of product"

      - name: brand
        data_type: string
        description: "product's brand"

      - name: product_type
        data_type: string
        description: "type of product: keyboard or keyboard kit"

      - name: keyboard_profile
        data_type: string
        description: "normal or low keyboard profile"

      - name: layout_size
        data_type: string
        description: "keyboard layout size"

      - name: layout_standard
        data_type: string
        description: "layout standard"

      - name: layout_ergonomics
        data_type: string
        description: "whether keyboard is normal, alice, split or ortholinear"

      - name: is_hot_swappable
        data_type: string
        description: "is the keyboard hot swappable"

      - name: has_knob_support
        data_type: string
        description: "does keyboard has knob support"

      - name: has_rgb_support
        data_type: string
        description: "does keyboard has rgb support"

      - name: has_display_support
        data_type: string
        description: "does keyboard has display support"

      - name: has_qmk_via
        data_type: string
        description: "does keyboard has QMK/VIA suport"

      - name: connection
        data_type: string
        description: "keyboard connection type wired, wireless, bluetooth, 2.4GHz"

      - name: is_wireless
        data_type: string
        description: "does keyboard has wireless  connection"

      - name: battery_capacity
        data_type: string
        description: "no battery, unknown or how many mAh of battery capacity"

      - name: mount_style
        data_type: string
        description: "keyboard mounting styles, how the plate or PCB is secured in the keyboard housing"

      - name: case_material
        data_type: string
        description: "material of keyboard case"

      - name: keycap_material
        data_type: string
        description: "material of included keycap"

      - name: scraping_date
        data_type: date
        description: "data scrapping date"

      - name: location
        data_type: string
        description: "keyboard vendor location"

      - name: stock_status
        data_type: string
        description: "stock status of each vendor"