models:
  - name: core_keyboards
    description: "all columns from joining base_keyboard_details and base_purchase_options models"
    columns:
      - name: product_tilte
        data_type: string
        description: ""

      - name: product_price
        data_type: int64
        description: ""

      - name: category_vendor
        data_type: string
        description: ""

      - name: category_voucher
        data_type: float64
        description: ""

      - name: is_new
        data_type: string
        description: ""

      - name: listing_link
        data_type: string
        description: ""

      - name: brand
        data_type: string
        description: ""

      - name: product_type
        data_type: string
        description: ""

      - name: keyboard_profile
        data_type: string
        description: ""

      - name: layout_size
        data_type: string
        description: ""

      - name: layout_standard
        data_type: string
        description: ""

      - name: layout_ergonomics
        data_type: string
        description: ""

      - name: is_hot_swappable
        data_type: string
        description: ""

      - name: has_knob_support
        data_type: string
        description: ""

      - name: has_rgb_support
        data_type: string
        description: ""

      - name: has_display_support
        data_type: string
        description: ""

      - name: has_qmk_via
        data_type: string
        description: ""

      - name: connection
        data_type: string
        description: ""

      - name: is_wireless
        data_type: string
        description: ""

      - name: battery_capacity
        data_type: string
        description: ""

      - name: mount_style
        data_type: string
        description: ""

      - name: case_material
        data_type: string
        description: ""

      - name: keycap_material
        data_type: string
        description: ""

      - name: scraping_date
        data_type: date
        description: ""

      - name: location
        data_type: string
        description: ""

      - name: stock_status
        data_type: string
        description: ""